name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html
    - name: Deploy
      uses: uibcdf/action-sphinx-docs-to-gh-pages@main
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dir_docs: docs/build/html        