name: Sphinx build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}    
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: hprepo
          environment-file: hp_environment.yml
      - name: install
        run: |
          conda env list
          conda info
          conda list
          conda install -c conda-forge pip          
          pip install --upgrade -e .          
          conda list
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.10'
    
    - name: Installing the Documentation requirements
      run: |
          pip3 install sphinx sphinx_rtd_theme

    - name: Deploy
      uses: uibcdf/action-sphinx-docs-to-gh-pages@main
      with:
        branch: main
        dir_docs: docs/source
